# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp193s0f0:
      addresses: [192.168.50.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 0 
      #NIC C
    enp193s0f1:
      addresses: [192.168.60.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 1
    enp193s0f2:
      addresses: [192.168.70.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 2
    enp193s0f3:
      addresses: [192.168.80.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 3
    enp1s0f0:
      addresses: [192.168.30.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 4
      #NIC B
    enp1s0f1:
      addresses: [192.168.40.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 5
    enp1s0f2:
      addresses: [192.168.10.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 6
    enp1s0f3:
      addresses: [192.168.20.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 7
    enp37s0f0:
      addresses: [192.168.11.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 8
      #NIC A
    enp37s0f1:
      addresses: [192.168.12.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 9
    enp37s0f2:
      addresses: [192.168.13.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 10
    enp37s0f3:
      addresses: [192.168.14.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 11
    enp225s0f0:
      addresses: [192.168.15.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 12
      #NIC D
    enp225s0f1:
      addresses: [192.168.16.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 13
    enp225s0f2:
      addresses: [192.168.17.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 14
    enp225s0f3:
      addresses: [192.168.18.1/24]
      gateway4: 0.0.0.0
      mtu: 9000
      #usrp 15
    